### ISSUE TITLE
Verificar quais serviços de clouds podemos subir o servidor de chat, seja por docker ou instalando as dependências

### ISSUE THREAD

**Issue by mikaelhadler** [ValorizeVidas/valorize-vidas#3]
Precisamos verificar qual serviço de cloud podemos utilizar, de forma gratuita preferencialmente.

- Google Cloud
- Umbler ( docker )

**Comment by iagocavalcante** [comment]
O que acham da Digital Ocean ?

**Comment by lucianmachado** [comment]
Qual os  principais requisitos para decidir o serviço cloud? Posso fazer um comparativo entre algumas plataformas para ajudar na escolha...

**Comment by mikaelhadler** [comment]
@iagocavalcante e @lucianmachado atualmente, devido a estrutura do MVP, acredito que não ser necessário um recurso como uma cloud, pois esta necessidade surgiu do princípio que teríamos que configurar o @livehelperchat em uma cloud para uso 'reduzido', mas em alinhamento com @gustavorps optamos por utilizar a o hosting da própria @livehelperchat pois o mesmo nos daria um custo de 6 euros mensais e não nos preocuparia-mos tanto com escalabilidade e problemas técnicos de fila, podendo dar todo foco as outras principais features.

Sendo assim, issue closed pessoal;
