### ISSUE TITLE
Finalizar layout da container 'Home'

### ISSUE THREAD

**Issue by mikaelhadler** [ValorizeVidas/valorize-vidas#33]
É necessário ajustar alguns pontos para que a home fique fiel ao layout proposto no Figma, segue a referência:

https://www.figma.com/file/KoFAagWzzSdf9x9RSV7rl53R/Valorize-Vidas?node-id=1%3A93

**Comment by juunegreiros** [comment]
Pode me dar assign nessa issue?

**Comment by mikaelhadler** [comment]
@juunegreiros Por gentileza, podes aceitar o convite para fazer o assign ? :+1:

**Comment by mikaelhadler** [comment]
Tem algum tempo estimado para esta tarefa @juunegreiros

**Comment by juunegreiros** [comment]
Entrego ela até amanhã!

**Comment by mikaelhadler** [comment]
@juunegreiros alguma novidade Ju ?

**Comment by juunegreiros** [comment]
Tinha ficado de fazer pair nessa issue com o Jhonata, mas vi que já deram continuidade nessa aqui também! Vou pegar outra pra tocar :)

**Comment by mikaelhadler** [comment]
Na real o Lucas Azevedo pegou a issue @juunegreiros, ele está trabalhando na parte responsiva do layout. Então acredito que essa issue já morra ao final do dia \o

**Comment by mikaelhadler** [comment]
Issue closed: #33
