### ISSUE TITLE
Criar component para menu de navegação

### ISSUE THREAD

**Issue by mikaelhadler** [ValorizeVidas/valorize-vidas#34]
É necessário criar o menu, conforme o layout proposto no Figma, veja os exemplos do menu colapsado e  não colapsado nas páginas:

- 'Home - Menu colapsado'
- 'Home - Menu expandido'

https://www.figma.com/file/KoFAagWzzSdf9x9RSV7rl53R/Valorize-Vidas?node-id=1%3A93

**Comment by miguelssrs** [comment]
eu posso fazer 🤙

**Comment by mikaelhadler** [comment]
Massa @miguelssrs por favor, se puder tocar essa issue, caso falte alguma informação, estamos a disposição.

**Comment by miguelssrs** [comment]
ok! provalmente vou consegui entregar só domingo que vem, mas é nóissss

**Comment by mikaelhadler** [comment]
Sem problemas @miguelssrs se quiser compartilhar o link da branch que irá trabalhar, talvez a galera possa ajudar \o

**Comment by mikaelhadler** [comment]
@miguelssrs herou, good news?

**Comment by miguelssrs** [comment]
tava freelando essas semanas e esqueci totalmente de fazer esse componente, me perdoa! vou fazer esse fim de semana <3 @mikaelhadler

**Comment by mikaelhadler** [comment]
Perfeito @miguelssrs, não tem problema, no teu tempo, todos temos vários corres, se agarrar em algo só gritar \o

**Comment by mikaelhadler** [comment]
@miguelssrs Opa, alguma novidade ? :]

**Comment by miguelssrs** [comment]
desculpa a sumida MASTER é que tava fazendo as tasks do trampo, de noite tenho cursinho pré vest e tava fazendo o material do quebradev (dou aula todo domingo) hahahah mas vou terminar, juro

**Comment by mikaelhadler** [comment]
@miguelssrs opa, novidades? :>

**Comment by mikaelhadler** [comment]
@rgosch thanks dude
