### ISSUE TITLE
Criar tela com o widget do LiveHelper Chat

### ISSUE THREAD

**Issue by mikaelhadler** [ValorizeVidas/valorize-vidas#36]
É necessário criar o component de widget que vai receber o embed do LiveHelper Chat conforme o layout proposto no Figma.

https://www.figma.com/file/KoFAagWzzSdf9x9RSV7rl53R/Valorize-Vidas?node-id=1%3A93

**Comment by lucasinocente** [comment]
Tem conta já do LiveHelper?

**Comment by mikaelhadler** [comment]
@lucasinocente Não, utilizei somente a nível de prototipação. Vou lhe enviar as informações do e-mail institucional, dai tu pode fazer este corre suavemente, beleza?

**Comment by mikaelhadler** [comment]
Feito decisão de utilizar o live helper da Rocket Chat.
