### ISSUE TITLE
Criar tela para formulário de contato

### ISSUE THREAD

**Issue by mikaelhadler** [ValorizeVidas/valorize-vidas#37]
É necessário criar a tela do formulário de contato conforme proposto no layout presente no Figma:

https://www.figma.com/file/KoFAagWzzSdf9x9RSV7rl53R/Valorize-Vidas?node-id=1%3A93

**Comment by lucasinocente** [comment]
Tem o google forms pronto já?

**Comment by mikaelhadler** [comment]
@lucasinocente Temos sim, só embedar e ja funciona zero bala.

**Comment by MateusGabi** [comment]
Olá, eu não entendi. Vai usar o google forms ou um próprio do projeto?

**Comment by mikaelhadler** [comment]
Exatamente Matheus, para não ter que lhe dar com controle de envios e feedback utilizamos o Google forms injetado no componente.

**Comment by MateusGabi** [comment]
@mikaelhadler então essa _issue_ já foi feita? Não tem nada a mais a ser implementado na tela de contato?

**Comment by ramon-src** [comment]
Desculpa a demora pra tocar esse ticket... Seria interessante termos um card para o formulário de Contato? 
Gostaria de saber também qual o propósito dessa tela de fato, o usuário que entrar em contato ele está buscando o que? Fiquei com essa dúvida! 
@mikaelhadler @MateusGabi @lucasinocente

**Comment by ramon-src** [comment]
Ajuste da largura do formulário vem no pull request numero #80
