### ISSUE TITLE
Criar tela de voluntariado

### ISSUE THREAD

**Issue by mikaelhadler** [ValorizeVidas/valorize-vidas#39]
É necessário criar a tela de voluntariado conforme layout proposto no Figma.

https://www.figma.com/file/KoFAagWzzSdf9x9RSV7rl53R/Valorize-Vidas?node-id=1%3A93

**Comment by lucasinocente** [comment]
Dá pra linkar direto pro apoia.se e usar como ferramenta principal pra simplificar e centralizar a comunicação.

Existe algum widget do apoia.se será pra embedar o botão de apoio?

**Comment by mikaelhadler** [comment]
@lucasinocente Dá sim, só não sei se existe algum badge ou widget pronto deles para embed, consegue dar uma olhada para nós ?

**Comment by mikaelhadler** [comment]
Feito análise e se torna muito mais prático redirecionar para a campanha direto.
