### ISSUE TITLE
Criar formulário de perguntas para pessoas que precisam de apoio emocional com risco de suicídio

### ISSUE THREAD

**Issue by mikaelhadler** [ValorizeVidas/valorize-vidas#5]
Deve se criar um formulário, assim como foi criado para os profissionais de saúde para saber mais informações do usuário que utiliza a CVV.

Precisamos saber quais são os maiores problemas enfrentados na plataforma pelos usuários, o que eles sugerem como melhoria e se canais de comunicação como Whatsapp, Telegram, Video Conferência seria algo válido para eles?

**Comment by jtlimo** [comment]
@mikaelhadler não consigo acessar a conta do valorize-vidas no typeform, fui tentar resetar a senha mas também não consegui acessar o email passado do valorize-vidas, fala que não existe.

**Comment by mikaelhadler** [comment]
@jtlimo feito contato contigo passando as informações de login, viste?

**Comment by jtlimo** [comment]
Vi sim @mikaelhadler ! Agora vou ter mais tempo pra tocar essa issue.

**Comment by mikaelhadler** [comment]
@jtlimo sem problemas, mas por favor, não for continuar com a issue, retire o assign por gentileza para que outros possam pegar está bem ? 

Qualquer dúvida podes me contactar por aqui ou por telegram esta bem ?

**Comment by mikaelhadler** [comment]
Esta issue foi fechada para ser organizada junto a novas milestones de marketing.
