### ISSUE TITLE
Ajustar tamanho dos icones e label nos cards

### ISSUE THREAD

**Issue by mikaelhadler** [ValorizeVidas/valorize-vidas#51]
Atualmente o Card está respeitando o tamanho do ícone e do label, é necessário que ele tenha tamanho fixo para o ícone e para o label.

**Comment by lhsazevedo** [comment]
Resolvido por #63 e #58

**Comment by ramon-src** [comment]
Quando puder, fechem mudem a posição no projeto para done :)
