### ISSUE TITLE
Criar logo do Valorize Vidas

### ISSUE THREAD

**Issue by mikaelhadler** [ValorizeVidas/valorize-vidas#6]
Deve se criar a logo do Valorize Vidas com algo que faça correlação com o simbolo de prevenção ao suicídio

**Comment by tghelere** [comment]
Temos algum design no time?

**Comment by italobarrosv** [comment]
Iae galera, estou seguindo o trabalho de vocês, trabalho de frontend mas curto muito a área de designer quando eu tiver algo pronto em relação  a logo eu mostro a vocês !

**Comment by tghelere** [comment]
Posso dar uma idéia?

**Comment by italobarrosv** [comment]
claro amigo, quanto mais informação melhor pra despertar a criatividade!

**Comment by tghelere** [comment]
Olhe esta logo que achei na internet, são dois Vs (o que serviria bem pra Valorize Vidas), mas note que se fizer o V de fora um pouco modificado, faz com que o espaço vazio (em branco) pareça um coração.

O que acham? Dá pra melhorar muito, é só um esboço de ideia. 

![captura de tela de 2018 11 29 16 41 23](https://user-images.githubusercontent.com/5022782/49244135-34e92880-f3f6-11e8-9eaa-8e6de3e57e32.png)

**Comment by mikaelhadler** [comment]
Olá @tghelere e @italobarrosv não temos um ux ou design oficial do projeto, por enquanto estamos aceitando colaborações.

Gostei da ideia, porém acho que ainda da pra melhorar colocando em vez de um 'V' no meio, colocar um coração, assim deixamos menos formal e com mais a cara de acolhedor, o que me diz @tghelere consegues reproduzir para nós? : ] :+1:

**Comment by mikaelhadler** [comment]
@tghelere @italobarrosv já estão em conversa para a produção desta issue, avancei o estado dela para doing beleza?

**Comment by italobarrosv** [comment]
bom dia galera fiz o esboço da logo,
usei o laço da prevenção fazendo um formato de 'v' minusculo com grafia de escrita a mão, enrolado no coração representando vida, a cor do laço um amarelo da campanha e para dar uma harmonia nao usei o vermelho puro mais sim um vermelho alaranjado
![vv_logo](https://user-images.githubusercontent.com/34260058/49330808-ad74f400-f572-11e8-83f7-8dc6fe8d0942.png)

**Comment by tghelere** [comment]
eu gostei pra cara...

**Comment by mikaelhadler** [comment]
Bah, ficou muito foda @italobarrosv curti demais!!!! Podemos utilizar esta mesmo ?

**Comment by kevinbreaker** [comment]
Ficou fod@ @italobarrosv, muito bom, parabéns.

**Comment by mikaelhadler** [comment]
@italobarrosv , conseguiu vetorizar pra nós ? assim que possível enviar pra nós <3

**Comment by mandyellow** [comment]
Gente, desculpa a demora, estava um pouco corrido para mim esses dias... Não sei se já fecharam mas fiz uma proposta. Abraços!

![ativo 1](https://user-images.githubusercontent.com/30158643/49484687-141e3a00-f81f-11e8-86a6-8bfa3890ceb8.png)

**Comment by mandyellow** [comment]
Gente, desculpa a demora, estava um pouco corrido para mim esses dias... Não sei se já fecharam mas fiz uma proposta. Abraços!

![ativo 2](https://user-images.githubusercontent.com/30158643/49484842-9a3a8080-f81f-11e8-8db2-243b1791fb5b.png)

**Comment by tghelere** [comment]
Gostei também!

**Comment by mikaelhadler** [comment]
Gente, estou muito feliz, ficou maravilhoso! Muito obrigado por essa contribuição @mandyellow !
