### ISSUE TITLE
Como o projeto funciona?

### ISSUE THREAD

**Issue by victorperin** [ValorizeVidas/valorize-vidas#72]
Oi pessoal, a @mandyellow me mostrou o projeto. Achei a idéia muito legal, mas não entendi muito bem como funciona.

Acho que a solução _(e para o pessoal que cair nesse repositório)_ seja ter uma descrição melhor no `README.md` de **como o projeto funciona**.

Enquanto isso, estou tentando rodar o projeto na minha maquina e fuçando, pra tentar ajudar com essa descrição, mas como vocês conhecem muito melhor, talvez possam me ajudar. hehe

**Comment by mikaelhadler** [comment]
Conforme conversamos pelo telegram, realmente é bem necessário a melhoria do README.md com informações sobre o escopo do projeto em sí, ao qual fizemos a primeira versão desta melhoria no PR #74
