### ISSUE TITLE
Adicionar lista de endereços do CVV no menu Endereços

### ISSUE THREAD

**Issue by ramon-src** [ValorizeVidas/valorize-vidas#76]

**Comment by MateusGabi** [comment]
O CVV tem um endpoint `https://www.cvv.org.br/search/cities?stateId={{UF}}` que retorna:

```
[
  {
    "id": "8853",
    "name": "Adamantina"
  },
  //...
]
```
A partir desse `id` faz a consulta por: `https://www.cvv.org.br/search/places?city_id={{ id }}`

```
[
  {
    "latitude": -21.6945452,
    "longitude": -51.0698024,
    "address": "Av. Vitório Romanini, 204.  Vila Cicma",
    "phone": "188",
    "time": "15 as 19 horas diariamente",
    "title": "Adamantina-SP"
  }
]
```

**CORS**: podemos usar `http://cors-anywhere.herokuapp.com/<url>` para resolver esse problema.

**Comment by mikaelhadler** [comment]
Issue closed #79
